name: Haven Image Analysis
description: The Face Detection API analyzes an image to find faces. It returns the position of the left and top edges of a bounding box that contains the face, and the width and height of the bounding box.
categories:
  - HavenOnDemand
labels:
  - RestApi
type: by-ref
default_service_version: 1.0
