name: MySQL
description: MySQL Database.
author: "Sushil Kumar"
category: Database
tags:
  - database
  - mysql
metadata:
  - first: sample

type: local   #by-ref, passthrough

default_service_version: 0
