name: Percona Cluster
description: Percona Galera Cluster
categories:
  - Database
labels:
  - database
  - mysql
  - percona
  - cluster
type: local   #by-ref, passthrough
default_service_version: 0
