name: Percona Cluster
description: Percona Galera Cluster
category: Database
tags:
  - database
  - mysql
  - percona
  - cluster
metadata:
  - first: sample

type: local   #by-ref, passthrough

default_service_version: 0
