name: ElasticSearch
description: Elasticsearch is a powerful open source search and analytics engine that makes data easy to explore.
category: Search
tags:
  - search
  - ElasticSearch
metadata:
  - first: sample

type: local   #by-ref, passthrough

default_service_version: 0
