name: Spark Cluster
description: Apache Spark Cluster
category: Big Data
tags:
  - bigdata
  - spark
  - apache
metadata:
  - first: sample

type: local   #by-ref, passthrough

default_service_version: 0
