name: AmazonRDSMySQL
description: Amazon RDS MySQL Database Server
categories:
  - Database
labels:
  - database
  - mysql
  - aws
type: by-ref
default_service_version: 1.0
is_supported: true
deployment_grade: production
